### ISSUE TITLE
Implementations of this spec

### ISSUE THREAD

**Issue by char0n** [JetBrains/http-request-in-editor-spec#6]
Hi, 

Great job on the spec. I was wondering, are there already some implementations in mainstream programming languages like JavaScript, Python, Elixir etc.. that implements parser for the specification and can run the .http files via CLI (except for runner in JetBrains IDEs) ? When we produce .http files and make them part of our CVS, we'd like to test them on CI to make sure we have .http files that reflects the reality.

Thank you!

**Comment by SvetlanaZem** [comment]
Hi, 

At the moment, there are no CLI runners for HTTP Requests but we have plans to create one: https://youtrack.jetbrains.com/issue/WI-42002

**Comment by char0n** [comment]
Thanks for pointing me into right direction.
