### ISSUE TITLE
[propose] Local variables

### ISSUE THREAD

**Issue by ccidral** [JetBrains/http-request-in-editor-spec#9]
# Request

Ability to declare local variables, i.e.: variables declared directly inside the HTTP requests file.

# Implementation

A fellow named Huachao Mao wrote an amazing HTTP client for VSCode from which we can get some inspiration: https://github.com/Huachao/vscode-restclient

The way he defines global variables is very nice and convenient. He uses the syntax `@variable_name=value`. Example:

```
@greeting=hello
@foo=123

###
POST http://localhost/something/{{foo}}

{
  "greeting": "{{hello}}"
}
```

**Comment by zinoviy23** [comment]
Thanks for request! I created issue for it: https://youtrack.jetbrains.com/issue/IDEA-240300

**Comment by zhupengfeivip** [comment]
More than a year later, there's still no answer to that question?  After testing, it still doesn't

**Comment by guinetik** [comment]
i just needed that, but yeah doesnt work yet

**Comment by QuAzI** [comment]
Still waiting for it

**Comment by QuAzI** [comment]
Still [actual](https://youtrack.jetbrains.com/issue/MP-5076/HTTP-Plugin-variables-defined-for-file)

**Comment by kevleyski** [comment]
Yeah this would be a neat feature - whilst can set up variables per run context, having simple named sustitutions in the .http file would be pretty useful

**Comment by zinoviy23** [comment]
Closing, because [corresponding YouTrack issue](https://youtrack.jetbrains.com/issue/IDEA-240300) is fixed.
Variables are expected in 2023.3 release.
